server:
  port: 80
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo2?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.base.dao.*Mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

